# Generated by Django 5.2.1 on 2025-05-23 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_consulta', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_de_inicio', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente_temporal', models.CharField(blank=True, help_text='Nombre del paciente si la cita es sin registro previo.', max_length=60, null=True)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PROGRAMADA', max_length=100)),
                ('pro_veri_cita', models.CharField(blank=True, choices=[('SOLICITADA', 'Cita solicitada'), ('CONFIRMACION_PENDIENTE', 'Confirmación pendiente'), ('RESPUESTA_OBTENIDA', 'Respuesta obtenida')], max_length=100, null=True)),
                ('fecha_hora_cita', models.DateTimeField(db_column='fecha')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('duracion_minutos', models.IntegerField(default=30)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('historial_cita', models.ForeignKey(blank=True, db_column='id_historial', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_asociada', to='citas.historialcita')),
                ('medico', models.ForeignKey(db_column='id_med', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='citas.medico')),
            ],
            options={
                'ordering': ['fecha_hora_cita'],
            },
        ),
        migrations.AddField(
            model_name='historialcita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales_cita', to='citas.paciente'),
        ),
    ]
