# Generated by Django 5.2.1 on 2025-05-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especialidad_texto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
